/*
 * oref - OpenAPS Reference Implementation in Rust
 * 
 * This file is auto-generated by cbindgen. Do not edit manually.
 * 
 * For iOS/Swift integration with Trio:
 * 1. Include this header in your bridging header
 * 2. Link against the liboref.a static library
 * 3. Use the oref_* functions to call the algorithms
 * 
 * Memory Management:
 * All string pointers returned by oref functions must be freed using
 * oref_free_string() to prevent memory leaks.
 */


#ifndef OREF_H
#define OREF_H

/* Generated with cbindgen:0.29.2 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#if defined(OREF_FFI)
/**
 * Free a string that was returned by an oref function.
 *
 * # Safety
 *
 * The pointer must have been returned by one of the oref functions,
 * and must not be used after this call.
 */
 void oref_free_string(char *ptr);
#endif

#if defined(OREF_FFI)
/**
 * Get the oref library version.
 *
 * # Returns
 * A null-terminated string containing the version. Must be freed with `oref_free_string`.
 */
 char *oref_version(void);
#endif

#if defined(OREF_FFI)
/**
 * Health check to verify the library is loaded correctly.
 *
 * # Returns
 * A JSON string containing status information. Must be freed with `oref_free_string`.
 */
 char *oref_health_check(void);
#endif

#if defined(OREF_FFI)
/**
 * Calculate Insulin on Board (IOB) from treatment history.
 *
 * # Safety
 *
 * - `profile_json` must be a valid null-terminated UTF-8 string containing Profile JSON
 * - `treatments_json` must be a valid null-terminated UTF-8 string containing Treatment[] JSON
 *
 * # Arguments
 * * `profile_json` - JSON string containing Profile data
 * * `treatments_json` - JSON string containing array of Treatment objects
 * * `time_millis` - Current time as Unix milliseconds
 * * `current_only` - If 1, only calculate current IOB (faster); if 0, calculate full array
 *
 * # Returns
 * JSON string containing IOBData array. Must be freed with `oref_free_string`.
 */

char *oref_calculate_iob(const char *profile_json,
                         const char *treatments_json,
                         int64_t time_millis,
                         int32_t current_only);
#endif

#if defined(OREF_FFI)
/**
 * Calculate current IOB only (optimized single-point calculation).
 *
 * # Safety
 *
 * Same requirements as `oref_calculate_iob`.
 */

char *oref_calculate_iob_current(const char *profile_json,
                                 const char *treatments_json,
                                 int64_t time_millis);
#endif

#if defined(OREF_FFI)
/**
 * Calculate Carbs on Board (COB) from glucose and treatment history.
 *
 * # Safety
 *
 * - `profile_json` must be a valid null-terminated UTF-8 string
 * - `glucose_json` must be a valid null-terminated UTF-8 string containing GlucoseReading[] JSON
 * - `treatments_json` must be a valid null-terminated UTF-8 string containing Treatment[] JSON
 *
 * # Arguments
 * * `profile_json` - JSON string containing Profile data
 * * `glucose_json` - JSON string containing array of GlucoseReading objects
 * * `treatments_json` - JSON string containing array of Treatment objects
 * * `time_millis` - Current time as Unix milliseconds
 *
 * # Returns
 * JSON string containing COBResult. Must be freed with `oref_free_string`.
 */

char *oref_calculate_cob(const char *profile_json,
                         const char *glucose_json,
                         const char *treatments_json,
                         int64_t time_millis);
#endif

#if defined(OREF_FFI)
/**
 * Calculate autosens ratio from glucose and treatment history.
 *
 * Detects changes in insulin sensitivity over time by analyzing
 * glucose deviations from expected values.
 *
 * # Safety
 *
 * All string pointers must be valid null-terminated UTF-8 strings.
 *
 * # Returns
 * JSON string containing AutosensData. Must be freed with `oref_free_string`.
 */

char *oref_calculate_autosens(const char *profile_json,
                              const char *glucose_json,
                              const char *treatments_json,
                              int64_t time_millis);
#endif

#if defined(OREF_FFI)
/**
 * Run the determine-basal algorithm.
 *
 * This is the main dosing algorithm that determines optimal temp basals and SMBs.
 *
 * # Safety
 *
 * `inputs_json` must be a valid null-terminated UTF-8 string containing DetermineBasalInputs JSON.
 *
 * # Returns
 * JSON string containing DetermineBasalResult. Must be freed with `oref_free_string`.
 */
 char *oref_determine_basal(const char *inputs_json);
#endif

#if defined(OREF_FFI)
/**
 * Convenience function to run determine_basal with individual parameters.
 *
 * # Safety
 *
 * All string pointers must be valid null-terminated UTF-8 strings.
 */

char *oref_determine_basal_simple(const char *profile_json,
                                  const char *glucose_status_json,
                                  const char *iob_data_json,
                                  const char *current_temp_json,
                                  double autosens_ratio,
                                  double meal_cob,
                                  int32_t micro_bolus_allowed);
#endif

#if defined(OREF_FFI)
/**
 * Calculate glucose status from readings.
 *
 * # Safety
 *
 * `glucose_json` must be a valid null-terminated UTF-8 string containing GlucoseReading[] JSON.
 *
 * # Returns
 * JSON string containing GlucoseStatus. Must be freed with `oref_free_string`.
 */
 char *oref_calculate_glucose_status(const char *glucose_json);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OREF_H */
