#!/usr/bin/env node --experimental-strip-types

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { jsonSchemaToZod } from "json-schema-to-zod";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const OPENAPI_PATH = path.join(
  __dirname,
  "../../packages/app/src/lib/api/generated/openapi.json",
);
const OUTPUT_PATH = path.join(
  __dirname,
  "../../packages/app/src/lib/api/generated/schemas.ts",
);

interface OpenApiSchema {
  openapi: string;
  components?: {
    schemas?: Record<string, object>;
  };
}

function generateZodSchemas(): void {
  console.log("Generating Zod schemas from OpenAPI spec...");

  if (!fs.existsSync(OPENAPI_PATH)) {
    console.error(`OpenAPI spec not found at: ${OPENAPI_PATH}`);
    console.error("Run 'pnpm run generate-api-client' first to generate the OpenAPI spec.");
    process.exit(1);
  }

  const openApiContent = fs.readFileSync(OPENAPI_PATH, "utf8");
  const openApi: OpenApiSchema = JSON.parse(openApiContent);

  if (!openApi.components?.schemas) {
    console.error("No schemas found in OpenAPI spec");
    process.exit(1);
  }

  const schemas = openApi.components.schemas;
  const schemaNames = Object.keys(schemas);
  console.log(`Found ${schemaNames.length} schemas to convert`);

  const lines: string[] = [
    "// Auto-generated from OpenAPI spec - DO NOT EDIT",
    "// Generated by: pnpm run generate-zod-schemas",
    `// Source: openapi.json (${new Date().toISOString()})`,
    "",
    "import { z } from 'zod';",
    "",
  ];

  // Build a map of all schema names for reference resolution
  const schemaNameSet = new Set(schemaNames);

  for (const [name, schema] of Object.entries(schemas)) {
    try {
      // Convert JSON Schema to Zod, replacing $ref with lazy references
      const schemaWithResolvedRefs = resolveRefsForGeneration(schema, schemaNameSet);

      const zodCode = jsonSchemaToZod(schemaWithResolvedRefs, {
        name: undefined, // We'll handle naming ourselves
        module: "none",
        noImport: true,
        withJsdocs: true,
      });

      lines.push(`export const ${name}Schema = ${zodCode};`);
      lines.push(`export type ${name} = z.infer<typeof ${name}Schema>;`);
      lines.push("");
    } catch (err) {
      console.warn(`Warning: Failed to convert schema '${name}':`, err);
      // Generate a fallback z.any() schema
      lines.push(`// Failed to generate schema for ${name}`);
      lines.push(`export const ${name}Schema = z.any();`);
      lines.push(`export type ${name} = z.infer<typeof ${name}Schema>;`);
      lines.push("");
    }
  }

  // Write the output file
  const output = lines.join("\n");
  fs.writeFileSync(OUTPUT_PATH, output, "utf8");
  console.log(`Generated ${schemaNames.length} Zod schemas at: ${OUTPUT_PATH}`);
}

/**
 * Resolve $ref references to inline schemas or replace with z.any() for circular refs
 */
function resolveRefsForGeneration(
  schema: unknown,
  schemaNames: Set<string>,
  visited = new Set<string>()
): unknown {
  if (schema === null || typeof schema !== "object") {
    return schema;
  }

  if (Array.isArray(schema)) {
    return schema.map((item) => resolveRefsForGeneration(item, schemaNames, visited));
  }

  const obj = schema as Record<string, unknown>;

  // Handle $ref
  if ("$ref" in obj && typeof obj.$ref === "string") {
    const refPath = obj.$ref as string;
    // Extract schema name from "#/components/schemas/SchemaName"
    const match = refPath.match(/#\/components\/schemas\/(\w+)/);
    if (match) {
      const refName = match[1];
      if (visited.has(refName)) {
        // Circular reference - use z.any()
        return {};
      }
      // For now, inline as z.any() to avoid complex lazy references
      // A more sophisticated approach would use z.lazy()
      return {};
    }
  }

  // Recursively process all properties
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    result[key] = resolveRefsForGeneration(value, schemaNames, visited);
  }
  return result;
}

// Run the generation
generateZodSchemas();

export default generateZodSchemas;
